# Generated by Django 5.1 on 2024-11-30 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('method', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_record', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key_value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('heart_rate', models.FloatField()),
                ('ambient_temperature', models.FloatField()),
                ('xyz_accelerometer', models.TextField()),
                ('is_exposed_to_light', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('base_url', models.TextField()),
                ('headers', models.JSONField()),
                ('endpoints', models.ManyToManyField(to='ServerApp.endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_name', models.TextField(unique=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerApp.key')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.TextField()),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('sex', models.TextField()),
                ('status', models.TextField()),
                ('record_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ServerApp.history')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='records',
            field=models.ManyToManyField(to='ServerApp.record'),
        ),
    ]
