# Generated by Django 5.1.3 on 2024-11-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('public_id', models.TextField()),
                ('name', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
