# Generated by Django 5.1 on 2025-01-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
