# Generated by Django 5.1 on 2024-11-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.TextField(default='Bilbao'),
            preserve_default=False,
        ),
    ]
