# Generated by Django 5.1 on 2025-01-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='reunions',
            field=models.ManyToManyField(blank=True, to='ServerApp.reunion'),
        ),
    ]
