# Generated by Django 5.1 on 2025-01-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0002_alter_reunion_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='xyz_accelerometer',
        ),
    ]
