# Generated by Django 5.1 on 2024-12-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
