# Generated by Django 5.1 on 2025-01-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0003_remove_record_xyz_accelerometer'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ip',
            field=models.TextField(default='192.168.1.0', unique=True),
            preserve_default=False,
        ),
    ]
