# Generated by Django 5.1.3 on 2024-11-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServerApp', '0003_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.TextField(),
        ),
    ]
